apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubewatch
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: kubewatch
  template:
    metadata:
      labels:
        app: kubewatch
    spec:
      serviceAccountName: kubewatch
      containers:
      - image: myregistry.azurecr.io/kubewatch:latest
        imagePullPolicy: Always
        name: kubewatch
        volumeMounts:
        - name: config-volume
          mountPath: /opt/root
        env: 
        - name: HOME
          value: "/opt/root"
        - name: KW_CONFIG
          value: "/opt/root"
      restartPolicy: Always
      volumes:
      - name: config-volume
        configMap:
          name: kubewatch1
